export enum TypeNotification {
    SOLICITUD = 'SOLICITUD_ENVIADA',
    SOLICITUD_ACEPTADA ='SOLICITUD_ACEPTADA',
    SOLICITUD_RECHAZADA = 'SOLICITUD_RECHAZADA',
    TAREA_AVANZADA ='TAREA_AVANZADA',
    TAREA_FINALIZADA='TAREA_FINALIZADA',
    NONE='NONE',
}